### ISSUE TITLE
Simultaor 6 and 22 do not start

### ISSUE THREAD

**Issue by userXinos** [webos-tools/webos-studio#8]
Hello, both versions (6, 22) crash immediately after the start, although there is also an error in versions 23 and 24, but the application continues to work

```bash
$ ./webOS_TV_6.0_Simulator_1.4.1.appimage

(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
[Success] The simulator launch is successful.
_0x59cc6a [Error]: connect ECONNREFUSED 0.0.0.0:443
    at Function._0x59cc6a.<computed> [as from] (/tmp/.mount_webOS_9cAaGJ/resources/app.asar/dist/main/main.js:7:154540)
    at _0x29bef5.<anonymous> (/tmp/.mount_webOS_9cAaGJ/resources/app.asar/dist/main/main.js:7:130504)
    at _0x29bef5.emit (events.js:210:5)
    at ClientRequest._0x4a9623.<computed> (/tmp/.mount_webOS_9cAaGJ/resources/app.asar/dist/main/main.js:13:130825)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  port: 443,
  address: '0.0.0.0',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED 0.0.0.0:443',
  name: 'Error',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function],
    transformRequest: [ [Function] ],
    transformResponse: [ [Function] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.28.0',
      'Content-Length': 302
    },
    method: 'post',
    url: 'https://www.google-analytics.com/mp/collect?measurement_id=G-452KJ9BF77&api_secret=vLu6x4NBS3e4riVT6SadWQ',
    data: '{"client_id":"35768ff6fd8a96036bc2b715f980b17ee99388fca8267951e364d3c44a613830","events":[{"name":"version_info","params":{"machineId":"35768ff6fd8a96036bc2b715f980b17ee99388fca8267951e364d3c44a613830","sessionId":"2cb6296d-093c-4462-8a8a-1ef74330c193","webOSTVVersion":"6.0","simulVersion":"1.4.1"}}]}'
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function],
      error: [Function],
      socket: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/mp/collect?measurement_id=G-452KJ9BF77&api_secret=vLu6x4NBS3e4riVT6SadWQ',
      method: 'POST',
      headers: [Object],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: _0x5e957d],
      beforeRedirects: [Object],
      hostname: 'www.google-analytics.com',
      port: null,
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/mp/collect',
      search: '?measurement_id=G-452KJ9BF77&api_secret=vLu6x4NBS3e4riVT6SadWQ'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 302,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /mp/collect?measurement_id=G-452KJ9BF77&api_secret=vLu6x4NBS3e4riVT6SadWQ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.28.0\r\n' +
        'Content-Length: 302\r\n' +
        'Host: www.google-analytics.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/mp/collect?measurement_id=G-452KJ9BF77&api_secret=vLu6x4NBS3e4riVT6SadWQ',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Circular],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://www.google-analytics.com/mp/collect?measurement_id=G-452KJ9BF77&api_secret=vLu6x4NBS3e4riVT6SadWQ'
  },
  cause: Error: connect ECONNREFUSED 0.0.0.0:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 443
  }
}
[93136:1229/172809.258049:FATAL:gpu_data_manager_impl_private.cc(990)] The display compositor is frequently crashing. Goodbye.
```

**Comment by YoungeunKim** [comment]
Hello, @userXinos ,

This is a TV simulator issue. Could you please register this issue on the LG TV Developer site (https://forum.webostv.developer.lge.com)?

Thanks.

**Comment by userXinos** [comment]
oh, terribly buggy site, somehow created a new account that logs in. Here is the [topic](https://forum.webostv.developer.lge.com/t/simultaor-6-and-22-do-not-start/17646), but for some reason there is no text


![img](https://github.com/user-attachments/assets/39d19843-7ecc-454f-9948-25001f70eace)

**Comment by YoungeunKim** [comment]
This issue was registered on the TV Developer Forum. I will close it in the webOS Studio's issue section.
(https://forum.webostv.developer.lge.com/t/simultaor-6-and-22-do-not-start/17646)
